config/routes.rb
Rails.application.routes.draw do
  root 'home#show'

  get 'auth/instagram',                                   as: :login
  get 'auth/instagram/callback',  to: 'sessions#create'
  get 'logout',                   to: 'sessions#destroy', as: :logout
  get 'users',                    to: 'users#show'

  namespace :users do
    resources :pictures, only: [:show]
  end


end

app/models/picture.rb
class Picture
  def self.all(service)
    pics = service.pictures
    pics[:data].map { |picture| build_object(picture) }
  end

  def self.find(service, media_id)
    pic = service.find_pic(media_id)
    build_object(pic[:data])
  end

  def self.pic_comments(service, media_id)
    comments = service.comments(media_id)
    comments[:data].map { |comment| build_object(comment)}
  end

  def self.pic_likes(service, media_id)
    likes = service.likes(media_id)
    likes[:data].map { |like| build_object(like) }
  end

  private

    def self.build_object(data)
      OpenStruct.new(data)
    end

end

app/models/user.rb
class User < ActiveRecord::Base

  def self.find_or_create_from_omniauth(auth_info)
    user = User.find_or_create_by(provider: auth_info["provider"], uid: auth_info['uid'])

    user.nickname       = auth_info['info']['nickname']
    user.name           = auth_info['info']['name']
    user.email          = auth_info['info']['email']
    user.image          = auth_info['info']['image']
    user.bio            = auth_info['info']['bio']
    user.website        = auth_info['info']['website']
    user.token          = auth_info['credentials']['token']

    user.save
    user
  end

  def self.profile(service)
    profile_info = service.user_info
    build_object(profile_info[:data])
  end

  private

    def self.build_object(data)
      OpenStruct.new(data)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :service

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def service
    @service ||= InstagramService.new(current_user) if current_user
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.find_or_create_from_omniauth(auth_info)
      session[:user_id] = user.id
      redirect_to users_path
    else
      redirect_to root_path
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

  private

    def auth_info
      request.env["omniauth.auth"]
    end
end

app/controllers/users/pictures_controller.rb
class Users::PicturesController < ApplicationController
  def show
    @picture = Picture.find(service, params[:id])
    @comments = Picture.pic_comments(service, params[:id])
    @likes = Picture.pic_likes(service, params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user_data = User.profile(service)
    @pictures = Picture.all(service)
  end

end

app/views/home/show.html.erb
<div class="container-fluid container-home">
  <div class="col-md-2"></div>
  <div class="col-md-4">
    <%= image_tag 'phones.png' %>
  </div>
  <div class="col-md-4 title">
    <h1 class="home">Welcome to <br />PictoNOW</h1>
    <h2 class="home">We're in the Sandbox!</h2>
    <%= link_to "Login with Instagram", "/auth/instagram", class: "btn btn-lg btn-default btn-home" %>
  </div>
  <div class="col-md-2"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PictoNow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_picture.html.erb
<div class="col-sm-6 col-md-3">
  <div class="thumbnail">
    <%= image_tag picture.images[:low_resolution][:url], class: "img-responsive" %>
    <div class="caption hide">
      <% if picture.caption  %>
        <h4><%= picture.caption[:text] %></h4>
      <% end %>
      <p>Likes:
        <%= picture.likes[:count] %> ||
        Comments:
        <%= picture.comments[:count] %></p>
        <p>Click for full info</p>
        <%= link_to "", users_picture_path(picture[:id]) %>
    </div>
  </div>
</div>

app/views/users/_profile.html.erb
<div class="row profile">
  <div class="col-md-2"></div>
  <div class="col-md-2">
    <%= image_tag current_user.image, class: "img-circle img-thumbnail home-image" %>
  </div>
  <div class="col-md-4">
    <h1 class="home"> <%= current_user.nickname %></h1>
    <h2 class="home"> <%= current_user.name %></h2>
    <h2 class="home"> <%= current_user.email %></h2>
    <h4 class="home"> <%= current_user.bio %> </h4>
    <h4 class="home"> <%= current_user.website %> </h4>

    <div class="row">
      <div class="col-md-4">
        <h4 class="following"><%= @user_data.counts[:media] %> posts</h4>
      </div>
      <div class="col-md-4">
        <h4 class="following"><%= @user_data.counts[:followed_by] %> followers</h4>
      </div>
      <div class="col-md-4">
        <h4 class="following"><%= @user_data.counts[:follows] %> following</h4>
      </div>
    </div>
  </div>
  <div class="col-md-2">
    <%= link_to "Logout", "/logout", class: "btn btn-lg btn-default btn-home" %>
  </div>
  <div class="col-md-2"></div>
</div>

app/views/users/pictures/_header.html.erb
<div class="row profile">
  <div class="col-md-2"></div>
  <div class="col-md-2">
    <%= image_tag current_user.image, class: "img-circle img-thumbnail home-image" %>
  </div>
  <div class="col-md-4">
    <h1 class="home"> <%= current_user.nickname %></h1>
  </div>
  <div class="col-md-2">
    <%= link_to "See All Pics", users_path, class: "btn btn-lg btn-default btn-home" %>
    <%= link_to "Logout", "/logout", class: "btn btn-lg btn-default btn-home" %>
  </div>
  <div class="col-md-2"></div>
</div>

app/views/users/pictures/show.html.erb
<div class="container-fluid container-home">
  <%= render partial: 'header' %>
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-4">
      <%= image_tag @picture.images[:standard_resolution][:url], class: "img-responsive" %>
    </div>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-body">
          <% if  @picture.caption%>
            <h3><%= @picture.caption[:text] %></h3>
            <hr />
          <% end %>
          <h4>Liked by:</h4>
          <p><%= @picture.likes[:count] %> users</p>
          <h4>Sandbox Likes From: </h4>
          <% @likes.each do |like| %>
            <p class="comment_name"><%= like.username %></p>
          <% end %>
          <h4>Sandbox comments:</h4>
          <% @comments.each do |comment| %>
            <p><span class="comment_name"><%= comment.from[:username] %></span> <%= comment.text %></p>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-2"></div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container-fluid container-home">
  <%= render partial: 'profile' %>
  <div class="row">
    <% @pictures.each do |picture| %>
      <%= render partial: 'picture', locals: { picture: picture} %>
      <% end %>
  </div>
</div>